#set keyboard layout
setxkbmap -layout br

#set language
export LANG=pt_BR.UTF-8

#start numlockx
numlockx &

#start compton
compton --config ~/.compton.conf -b

#start xmonad
#exec xmonad
exec awesome -c ~/.awesome/rc.lua
